# Generated by Django 4.2.7 on 2024-01-08 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="", max_length=70, verbose_name="Название бренда"
                    ),
                ),
                (
                    "desc_brand",
                    models.TextField(max_length=2000, verbose_name="Описание бренда"),
                ),
                (
                    "site_brand",
                    models.TextField(max_length=50, verbose_name="Сайт бренда"),
                ),
                (
                    "brand_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["brand_name"],
            },
        ),
        migrations.CreateModel(
            name="Tastes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_taste",
                    models.CharField(
                        default="", max_length=90, verbose_name="Название вкуса"
                    ),
                ),
                (
                    "taste_rus",
                    models.CharField(
                        default="", max_length=90, verbose_name="Русское название вкуса"
                    ),
                ),
                (
                    "desc_taste",
                    models.TextField(max_length=2000, verbose_name="Описание вкуса"),
                ),
                (
                    "taste_image",
                    models.ImageField(
                        default="taste_images/default_taste.jpg",
                        upload_to="tastes_images",
                    ),
                ),
                ("strength_taste", models.IntegerField(verbose_name="Крепость вкуса")),
                (
                    "brand_id",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.brands",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вкус",
                "verbose_name_plural": "Вкусы",
                "ordering": ["name_taste"],
            },
        ),
    ]
