# Generated by Django 4.2.7 on 2023-12-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="", max_length=70, verbose_name="Название бренда"
                    ),
                ),
                (
                    "desc_brand",
                    models.TextField(max_length=350, verbose_name="Описание бренда"),
                ),
                (
                    "site_brand",
                    models.TextField(max_length=50, verbose_name="Сайт бренда"),
                ),
                (
                    "brand_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
