# Generated by Django 4.2.7 on 2024-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_brands_brand_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brands",
            name="desc_brand",
            field=models.TextField(
                default="", max_length=2000, verbose_name="Описание бренда"
            ),
        ),
    ]
