# Generated by Django 4.2.7 on 2024-01-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_brands_desc_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tastes",
            name="brand_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.brands",
            ),
        ),
    ]
