# Generated by Django 4.2.7 on 2023-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_image",
            field=models.ImageField(
                default="account_images/default_user.jpg", upload_to="account_images"
            ),
        ),
    ]
