# Generated by Django 4.2.7 on 2024-01-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_tastes_taste_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_favorite_taste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite_taste",
            name="taste_id_favorite",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tastes",
            ),
        ),
        migrations.AlterField(
            model_name="favorite_taste",
            name="user_id_favorite",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
