# Generated by Django 4.2.7 on 2024-01-08 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_tastes_taste_image"),
        ("users", "0003_alter_favorite_taste_taste_id_favorite_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite_taste",
            unique_together={("user_id_favorite", "taste_id_favorite")},
        ),
    ]
