# Generated by Django 4.2.7 on 2024-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_favorite_taste_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
